version: "3.8"

services:
  booktrack:
    container_name: booktrack
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_DATABASE=booktrack
    ports:
      - '3307:3306'
    networks:
      - backend
    volumes:
      - mysql-booktrack:/var/libs/mysql


volumes:
  mysql-booktrack: 
networks:
  backend: